# Generated by Django 3.2.12 on 2022-11-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tag'),
        ),
    ]
