# Generated by Django 3.2.12 on 2022-11-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tag'),
        ),
    ]
