# Generated by Django 3.2.12 on 2022-11-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_educationaldetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='myapp.personaldetails'),
        ),
    ]
