# Generated by Django 3.2.12 on 2022-11-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_educationaldetails_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationaldetails',
            name='user_id',
        ),
    ]
