# Generated by Django 3.2.12 on 2022-11-28 08:08

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_educationaldetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedetails',
            name='user_id',
            field=models.ForeignKey(default=myapp.models.CertificateDetails.fetch_userid, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.personaldetails'),
        ),
        migrations.AlterField(
            model_name='educationaldetails',
            name='user_id',
            field=models.ForeignKey(default=myapp.models.EducationalDetails.fetch_userid, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.personaldetails'),
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.skills')),
                ('user_id', models.ForeignKey(default=myapp.models.WorkDetails.fetch_userid, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.personaldetails')),
                ('year_exp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.yearsofexp')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=80)),
                ('employer', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.country')),
                ('from_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.years')),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.state')),
                ('to_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to', to='myapp.years')),
                ('user_id', models.ForeignKey(default=myapp.models.EmploymentHistory.fetch_userid, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='AwardsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('award_org', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(default=myapp.models.AwardsDetails.fetch_userid, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.personaldetails')),
            ],
        ),
    ]
