# Generated by Django 3.2.12 on 2022-11-28 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20221128_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workdetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PreferencesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=80)),
                ('has_passport', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.years')),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.country')),
                ('industry_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.industries')),
                ('salary_exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.salaryexp')),
                ('user_id', models.ForeignKey(default=myapp.models.PreferencesDetails.fetch_userid, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.personaldetails')),
            ],
        ),
    ]
