# Generated by Django 3.2.12 on 2022-12-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20221201_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='restaurants_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
