# Generated by Django 3.2.12 on 2022-12-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_restaurants_restaurants_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='restaurants_id',
            field=models.ManyToManyField(to='myapp.Restaurants'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='restaurants_name',
            field=models.CharField(max_length=100),
        ),
    ]
