# Generated by Django 3.2.12 on 2022-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20221201_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='restaurants_id',
            field=models.ManyToManyField(related_name='restaurants', to='myapp.Restaurants'),
        ),
    ]
